### PR TITLE
Prepare release of version 1.0.0 of the SDK

### PR DESCRIPTION
**Pull request by peterwvj**

### CODE REVIEW

**Review by monsieurtanuki — COMMENTED** [review]
I understand how important it can be to quickly make available a null-safe version.
But as @M123-dev or @stephanegigandet (can't remember) pointed out, some fields must definitely never be null, but as far as the migration went they're still `?` nullable.
I'm OK with a quick null-safe version (today?) as long as we're comfortable with the following breaking changes that will probably happen: "OK guys, this field is finally mandatory, sorry about that, we won't stay forever with a nullable field".

**Comment by M123-dev** [comment]
We can probably release as a beta with a big disclaimer.

**Comment by peterwvj** [comment]
Hi @monsieurtanuki thanks for your input. We can wait for a bit with releasing a new version of the SDK if people generally agree it needs additional "post migration" adjustments. By language design, all fields were nullable prior to migration. Whether we choose to introduce additional breaking changing now (non-nullable fields) with a fast release or a bit later I don't think makes much of a difference. Let's see what the other guys think.

**Review by MohamedFBoussaid — COMMENTED** [review]
🎉🎉🎉🎉

**Comment by MohamedFBoussaid** [comment]
> 🎉🎉🎉🎉

I agree with @M123-dev to release on beta, and we can tested and once we are sure of the beta version we can pass to 1.0.0

**Comment by peterwvj** [comment]
That would work for me as well :)

**Comment by peterwvj** [comment]
Alright, I updated the PR to use `1.0.0-beta` instead per your suggestions.

**Review by MohamedFBoussaid — APPROVED** [review]

**Pull request merged**
