### PR TITLE
feature_2/#191 - added eco-score and nutri-score categories (ProductImprovement)

### PR DESCRIPTION
**Pull request by monsieurtanuki**
Impacted file:
* `Product.dart`

### CODE REVIEW

**Review by M123-dev — APPROVED** [review]
👍🏼

**Comment by M123-dev** [comment]
Just one sidenote @monsieurtanuki, the changelog is going to be created by [release-please](https://github.com/google-github-actions/release-please-action) and it doesn't leave much tolerance for commit names (in my testing, even a capital F at fix: was not accepted), so I assume that such names as this will not be automatically included.

**Comment by monsieurtanuki** [comment]
@M123-dev Oh, I wasn't aware of that. In that case a correct title would have been "feat: #191 - added eco-score and nutri-score categories (ProductImprovement)", am I right?

**Comment by M123-dev** [comment]
@monsieurtanuki according to the dokumentaion it looks right. With a little testing, we will quickly find the right syntax.

**Pull request merged**
