### PR TITLE
Prepare release of v0.3.15+3

### PR DESCRIPTION
**Pull request by stephanegigandet**
Let's see how many pub points we get with all your improvements. :)

### CODE REVIEW

**Review by MohamedFBoussaid — APPROVED** [review]
All good.

**Review by peterwvj — APPROVED** [review]
Thanks!

**Comment by monsieurtanuki** [comment]
[Looks good](https://pub.dev/packages/openfoodfacts/score), doesn't it?

Capture d’écran 2021-03-01 à 20 53 04

The only problem left is with the comments. The only way to fix that is to thoroughly add comments:
> 0/10 points: 20% or more of the public API has dartdoc comments
45 out of 1615 API elements (2.8 %) have documentation comments.
Providing good documentation for libraries, classes, functions, and other API elements improves code readability and helps developers find and use your API. Document at least 20% of the public API elements.

**Comment by MohamedFBoussaid** [comment]
@monsieurtanuki indeed, maybe we can go thought the old code and add comments, and for the future PR we take comments as a must to approved.

**Comment by monsieurtanuki** [comment]
Sure, @MohamedFBoussaid.
Hey code reviewers: no code approval without classes and functions being properly `///` commented!
That's too bad `pana` doesn't tell the current percentage of commented items.

**Pull request merged**
