### PR TITLE
Extended micronutrients support

### PR DESCRIPTION
**Pull request by indigothm**
I needed extended support for micronutrients. So additional units and nutrients were added and tested.

### CODE REVIEW

**Comment by teolemon** [comment]
Thanks a lot @indigothm :-)
Just curious: is your app out yet ?
I've asked the Dart team for review

**Comment by teolemon** [comment]
@indigothm can you rebase your PR ?

**Comment by peterwvj** [comment]
In addition to the conflicts, there are failing tests. Part of this is due to the sad fact that the the the tests test against the database, which changes. Although this is bad, we should insist that all tests pass before merging a PR. For now, please update the expected values to reflect the actual ones retrieved from the database - which is a simply, but tedious task (this PR isn't expected to fix the actual problem with the tests) and look for "genuine" test failures that could be caused by the changes introduced by this PR.

**Comment by teolemon** [comment]
@peterwvj @indigothm @openfoodfacts/openfoodfacts-dart I've solved the conflicts.

**Comment by Grumpf86** [comment]
I've found small issues with these tests:
- api_getProducts_test
- api_searchProduct_test
but these tests fail also on the master-branch. So I will merge now and fix those two tests afterwards,

**Comment by teolemon** [comment]
Congratulation @indigothm on your first PR to @openfoodfacts/openfoodfacts-dart 🎉

**Pull request merged**
