### PR TITLE
Updated Readme.md

### PR DESCRIPTION
**Pull request by yashsharma81**
### What
- 

### Fixes bug(s)
- 

### Part of 
-

### CODE REVIEW

**Comment by yashsharma81** [comment]
This is temporary solutions for showing scores. so that UX doesn't compromise I'm working on API

**Comment by M123-dev** [comment]
Heyy @yashsharma81 I think you meight missunderstood the problem. The score batches are working perfectly. The problem is with the license. I guess we edited the license so that it isn't automatically detected anymore. This should be fixed if we get the correct Apache License 2.0 text any only change the to be changed text fields

**Comment by yashjani01** [comment]
@M123-dev okay i understood now

**Comment by M123-dev** [comment]
I think we can close this for now, can't we @yashjani01 ?

If not feel free to reopen or create a new PR

**Pull request closed without merging**
