### PR TITLE
chore: LICENSE 2024

### PR DESCRIPTION
**Pull request by monsieurtanuki**
### What
- Updated the LICENSE to 2024.

### Part of 
- #643

### CODE REVIEW

**Review by teolemon — APPROVED** [review]
Happy birthday 🍰 :-)

**Comment by monsieurtanuki** [comment]
> Happy birthday 🍰 :-)

Merci Pierre !

**Comment by M123-dev** [comment]
Also happy Birthday from me, I hope you'll have a great day 🎉🎁

**Comment by monsieurtanuki** [comment]
Danke Marvin! So far a very good day ;)

**Pull request merged**
