### PR TITLE
fix_6/#90 - added comments to classes and methods in folder "utils"

### PR DESCRIPTION
**Pull request by monsieurtanuki**
There are still classes to add comments to in this folder, but this is a quick PR.

Impacted files:
* `ImageHelper.dart`
* `JsonHelper.dart`
* `LanguageHelper.dart`
* `NutrimentsHelper.dart`
* `PnnsGroupQueryConfiguration.dart`
* `PnnsGroups.dart`
* `ProductFields.dart`
* `ProductHelper.dart`
* `QueryType.dart`
* `UnitHelper.dart`

### CODE REVIEW

**Review by peterwvj — APPROVED** [review]
Great work, thanks!

**Comment by monsieurtanuki** [comment]
Very busy today, don't know why! :)
Thank you @peterwvj @M123-dev @MohamedFBoussaid for your code reviews and comments in the last 2 days.

**Comment by M123-dev** [comment]
@monsieurtanuki. it has a good purpose. A 130 score would be awesome

**Comment by monsieurtanuki** [comment]
@M123-dev Sure! The problem is that I could not find a way to pre-compute how good we are for the comments. There's a threshold of 20% of comments (cf. https://pub.dev/packages/openfoodfacts/score):
> 0/10 points: 20% or more of the public API has dartdoc comments
80 out of 1786 API elements (4.5 %) have documentation comments.

The idea now is to systematically add dart comments for new classes and methods.
And to add comments once in a while for older code.
By the time we upload to pub.dev maybe we'll go beyond the 20% barrier and get the last 10 points!

**Pull request merged**
