### PR TITLE
feat: added "origins" field to product

### PR DESCRIPTION
**Pull request by monsieurtanuki**
Impacted files:
* `Product.dart`: added "origins" field
* `Product.g.dart`: generated
* `ProductFields.dart`: added "origins" field

### What
- added "origins" field to product

### Part of 
- https://github.com/openfoodfacts/smooth-app/issues/2501

### CODE REVIEW

**Review by M123-dev — APPROVED** [review]

**Comment by M123-dev** [comment]
We should probably add simple tests for that though

**Comment by monsieurtanuki** [comment]
Thank you @M123-dev!
Actually we should refactor the whole `getProduct` tests here, probably on PROD data.

**Comment by M123-dev** [comment]
The next thing on the todo list

**Comment by monsieurtanuki** [comment]
The next thing on the todo list should rather be tests that work, which is not the case anymore, cf. #500.

**Pull request merged**
