### PR TITLE
Update test-sdk.yml

### PR DESCRIPTION
**Pull request by M123-dev**

### CODE REVIEW

**Comment by peterwvj** [comment]
Thanks, the new GH action picks up some new problems though

Screenshot_20210306-064442_Chrome

**Review by peterwvj — APPROVED** [review]

**Review by monsieurtanuki — COMMENTED** [review]
Hi @M123-dev!
Disclaimer: I have no idea what this file is made for, and I don't know the impact of your changes either.
AFAIK your change looks reasonable.

**Comment by monsieurtanuki** [comment]
@peterwvj Regarding your comment, it looks like the problem comes from code like this:
```dart
@JsonKey(nullable: false)
  String text;
```
Maybe `String? text` would be enough, while removing the `nullable: false` parameter?

**Comment by M123-dev** [comment]
@monsieurtanuki @peterwvj Thanks for your review. The new infos in the analyzer are coming from the upgraded packages. I left them inside bc I guess they will be an important info when upgrading to null-safety.

**Pull request merged**
