### PR TITLE
feat: 688 - new method "getProductImageIds"

### PR DESCRIPTION
**Pull request by monsieurtanuki**
New file:
* `api_get_product_image_ids_test.dart`: tests around `OpenFoodAPIClient.getProductImageIds`.

Impacted files:
* `image_helper.dart`: new method `getUploadedImageUrl`
* `open_food_api_client.dart`: new method `getProductImageIds`

### What
- New method `getProductImageIds`, that returns all uploaded image ids for a `Product`.

### Fixes bug(s)
- #688

### CODE REVIEW

**Comment by monsieurtanuki** [comment]
@M123-dev Oops, I need to add something important...

**Comment by monsieurtanuki** [comment]
Now it's OK for review.

**Comment by monsieurtanuki** [comment]
@stephanegigandet Just curious: I've just detected a change about product `0028400047685` regarding `forest_footprint`. And the product's last change was in December 2020...
I believe there's a new ambiguity between a `known` status, a bad score and an attribute not supposed to be computed; anyway the off-dart tests started to fail recently, and I was wondering if you guys changed something on the server side regarding `forest_footprint`.

```json
{
	"description": "",
	"description_short": "Pour l'instant seulement pour les produits avec du poulet ou des oeufs",
	"grade": "e",
	"icon_url": "https://static.openfoodfacts.net/images/attributes/forest-footprint-not-computed.svg",
	"id": "forest_footprint",
	"match": 0,
	"name": "Empreinte forêt",
	"status": "known",
	"title": "Empreinte forêt non calculée"
}
```

**Review by M123-dev — APPROVED** [review]
LGTM, thanks @monsieurtanuki

**Comment by monsieurtanuki** [comment]
Thank you @M123-dev for the review!

**Pull request merged**
