### PR TITLE
Test to reproduce fromJson bug #201

### PR DESCRIPTION
**Pull request by stephanegigandet**
Test to reproduce #201

Unfortunately no solution yet.

### CODE REVIEW

**Review by monsieurtanuki — COMMENTED** [review]
@stephanegigandet I would recommend to comment all the `languages` fields until we find a solution.

**Comment by monsieurtanuki** [comment]
@stephanegigandet I've just fixed it. Please have a look at my code, and merge if relevant.

**Comment by stephanegigandet** [comment]
> @stephanegigandet I've just fixed it. Please have a look at my code, and merge if relevant.

I can't approve my own PR but your fix looks good to me and it makes the test pass. :)

**Comment by monsieurtanuki** [comment]
@stephanegigandet You cannot approve your own code but you can merge it all the same.
Assuming it makes sense compared to #203.

**Pull request merged**
