### PR TITLE
feat: #596 - added Origin Taxonomy

### LINKED ISSUE #596: Add support for the Origins taxonomy
### What
- [ ] Add support for the Origins taxonomy
  - [x] We need support for autocomplete for the origin field: https://world.openfoodfacts.org/cgi/suggest.pl?tagtype=origins&term=fr&lc=en
  - [ ] We need support for the Partial taxonomy API

### Why
- https://github.com/openfoodfacts/smooth-app/issues/3149

### PR DESCRIPTION
**Pull request by monsieurtanuki**
New files:
* `api_getTaxonomyOriginsServer_test.dart`: server tests around Origin Taxonomy
* `TaxonomyOrigin.dart`: Origin Taxonomy classes
* `TaxonomyOrigin.g.dart`: generated

Impacted file:
* `openfoodfacts.dart`: added method `getTaxonomyOrigins`; reformated the `getTaxonomy*` methods

### What
- Last part of #596, with method `getTaxonomyOrigins`

### Fixes bug(s)
- Closes #596

### CODE REVIEW

**Review by teolemon — COMMENTED** [review]
I don't understand all the mentions of languages and countries throughout the code, as we have dedicated routes for the origins taxonomy. Could you provide some context ?

**Comment by monsieurtanuki** [comment]
> I don't understand all the mentions of languages and countries throughout the code, as we have dedicated routes for the origins taxonomy. Could you provide some context ?

Like the other taxonomies, we provide language and country in order to get taxonomies, if only for localization.
Could you be more specific about what troubles you in my code?

**Comment by teolemon** [comment]
Ah ok, to get it in the right language?

**Comment by monsieurtanuki** [comment]
> Ah ok, to get it in the right language?

Indeed. Again, that's the same for the other taxonomies.

**Review by M123-dev — APPROVED** [review]
LGTM, thanks @monsieurtanuki

**Comment by monsieurtanuki** [comment]
Thank you @M123-dev!

**Pull request merged**
