### PR TITLE
Setting default language to OpenFoodFactsLanguage.WORLD and fields to…

### PR DESCRIPTION
**Pull request by MohamedFBoussaid**
Setting default language to OpenFoodFactsLanguage.WORLD and fields to ProductField.ALL if user does not provide them. 
Adding tests to cover changes. 
Updating tests.

### CODE REVIEW

**Review by stephanegigandet — APPROVED** [review]
Looks good, thank you!

**Review by stephanegigandet — CHANGES_REQUESTED** [review]
I approved this too fast. In fact the OFF API has no "world" language. There is only a "world" country.

We should either force the apps to specify a language, or use English as the default. (which is what the API assumes if no language is passed).

**Comment by MohamedFBoussaid** [comment]
@stephanegigandet , my bad. I will fix this and set it to EN.

**Comment by MohamedFBoussaid** [comment]
@stephanegigandet I have rebased my branch on the latest changes on the master. And with your changes on  #76, no need anymore to set a default value for the language. I am only setting the field to ALL in case this was not provided on the configuration.

**Review by stephanegigandet — APPROVED** [review]
Thank you!

**Pull request merged**
