### PR TITLE
ci: Add an action to check for semantic PRs titles

### PR DESCRIPTION
**Pull request by teolemon**
### What
Add an action to check for semantic PRs titles

### CODE REVIEW

**Comment by M123-dev** [comment]
What does this Action do

**Comment by teolemon** [comment]
it checks whether there's a prefix in the PR title's name, and warns if not

**Comment by M123-dev** [comment]
Sp fix: feat: ... right?

**Comment by teolemon** [comment]
Yes

**Review by M123-dev — APPROVED** [review]

**Pull request merged**
