### PR TITLE
docs: prepare release of version 1.2.0 of the SDK

### LINKED ISSUE #173: New release
The latest release on pub.dev is from the 30.03, lets make a new one.

Also, let's release the new version as latest and not as preversion. Smoothie uses the preversion, there are no bugs and null-safety has been mainstream for a while now.

### PR DESCRIPTION
**Pull request by peterwvj**
Closes #173

### CODE REVIEW

**Review by MohamedFBoussaid — APPROVED** [review]
All good thanks @peterwvj

**Review by M123-dev — APPROVED** [review]
Thanks, @peterwvj

**Comment by MohamedFBoussaid** [comment]
@peterwvj Does it take time to be pushed to pub.dev ? 
I can't see the 1.2.0 version.

**Comment by peterwvj** [comment]
Hi @MohamedFBoussaid sorry I forgot to publish the package, it's out now https://pub.dev/packages/openfoodfacts

**Comment by peterwvj** [comment]
If you want permissions to publish new releases then maybe try to reach out to @PrimaelQuemerais on Slack. I think it was him who granted me the permissions.

**Comment by MohamedFBoussaid** [comment]
image

@peterwvj 😍😍🤘🏽🤘🏽

**Pull request merged**
