### PR TITLE
test: Signup tests

### PR DESCRIPTION
**Pull request by M123-dev**
### What
- Fixes: #541
- For: https://github.com/openfoodfacts/smooth-app/issues/1239

### CODE REVIEW

**Comment by M123-dev** [comment]
Heyy @g123k @monsieurtanuki for some reason I can't get the signup to work. I always recieve a 400 code with and Unkown error, on the website the register works and the multipart parameters seem right (used the same generated credentials so the register process really did not work). Do you have any idea

**Comment by monsieurtanuki** [comment]
@M123-dev No idea where the problem comes from. Just a general idea: in TEST env things don't work smoothly.

**Comment by M123-dev** [comment]
So after way to long debugging of the authentication method we use as it was a 401 status code I found the problem. We didn't pass the queryType in the login method. Thats now fixed 🥳

**Comment by M123-dev** [comment]
Thanks for your review @monsieurtanuki

**Pull request merged**
