### PR TITLE
Robotoff support

### PR DESCRIPTION
**Pull request by PrimaelQuemerais**
I've added the ability to get and answer Robotoff questions & insights :
- GET random insight
- GET product insights
- GET questions for product
- GET random questions
- POST insight (answer to a question)
- GET ingredient spelling corrections

### CODE REVIEW

**Comment by PrimaelQuemerais** [comment]
This branch also contains the Documentation I've written so accepting this pull request will add the documentation to the Master branch

**Comment by Grumpf86** [comment]
Wow, I didn't know about robotoff until now. :) I will have a detailed look at the weekend.

**Comment by Grumpf86** [comment]
The implementation looks good to me. But not all the unit tests are passing. Product 3274570800026 has no questions anymore. Will the question disappear, if it get answered?

And we should find some subfolder structure for the increasing amout of our model classes. But this doesn't has do be done in this issue. feel free :)

**Comment by PrimaelQuemerais** [comment]
Nice. Yes questions are removed when answered that's why the test is not passing. Can we merge anyway ?

Sure, let's do that once the current changes are merged, I've approved #21 ;)

**Pull request merged**
