### PR TITLE
feat: 893 - 4 new fields for user

### PR DESCRIPTION
**Pull request by monsieurtanuki**
### What
- Now when we log in we get 4 fields:
  - preferredLanguage
  - country
  - isModerator
  - isAdmin
- And we don't get the "email" field anymore.
- @stephanegigandet Still a problem on the server side: we get `country` as `en:france`, which is not very easy to convert, whereas `fr` would be perfect

### Fixes bug(s)
- Closes: #893

### Impacted files
* `login_status.dart`: added 4 fields and deprecated "email"
* `open_food_api_client.dart`: upgraded the max length of user name (60) and user id (40)
* `user_management_test_prod.dart`: tested the new 4 login status fields
* `user_management_test_test_env.dart`: tested the new 4 login status fields and remove a test on "email"

### CODE REVIEW

**Comment by stephanegigandet** [comment]
@monsieurtanuki PR to add a cc field: https://github.com/openfoodfacts/openfoodfacts-server/pull/10152 ("world" can also be a value)

**Comment by monsieurtanuki** [comment]
@stephanegigandet I've just PR'ed the use of json field `'cc'` instead of `'country'`.

As mentioned in https://github.com/openfoodfacts/openfoodfacts-server/pull/10152#issuecomment-2068091511, so far I couldn't test it successfully in PROD as the field doesn't seem to be available.

Besides, I'm not 100% sure it would be very clean to add a fake country called `'world'`.
Wouldn't `null` instead of `'world'` still work? For the record that is what is happening right now, as we cannot decode `'world`' as a country and decode it as `null`.

**Comment by monsieurtanuki** [comment]
Thank you @stephanegigandet: I've just tested in PROD and the `cc` field is now populated.

**Comment by monsieurtanuki** [comment]
ping

**Review by M123-dev — APPROVED** [review]
The dart side is looking fine 💯

**Comment by monsieurtanuki** [comment]
Thank you @M123-dev for your review!

**Pull request merged**
