### PR TITLE
feat: #370 - added "uuid" to configuration

### PR DESCRIPTION
**Pull request by monsieurtanuki**
Impacted files:
* `configuration_test.dart`: added tests with "uuid"
* `HttpHelper.dart`: included new static `uuid` to parameters
* `OpenFoodAPIConfiguration.dart`: added `static String? uuid`
* `pubspec.yaml`: unrelated upgrade

### CODE REVIEW

**Review by M123-dev — APPROVED** [review]
Looks good thanks

**Comment by monsieurtanuki** [comment]
Thank you @M123-dev for your review!
Now the trick is to tell developers to use user agent and uuid, but that's beyond my coding abilities ;)

**Comment by MohamedFBoussaid** [comment]
@monsieurtanuki thank you for the changes. Maybe updating the readMe and the example file can help ? 
So by default when someone will start coding with OFF package will coy/paste the example with the uuid

**Comment by M123-dev** [comment]
That's something we can add to https://github.com/openfoodfacts/openfoodfacts-dart/projects/2

**Comment by monsieurtanuki** [comment]
Fair enough @MohamedFBoussaid, but I don't know
1. which values can be set - [strict UUID format](https://en.wikipedia.org/wiki/Universally_unique_identifier#Format) or just a String?
=> probably just a String
2. how the developers get a UUID - they just import whatever uuid package or they call an OFF dedicated API, as @jasmeet0817 feared that UUID may not be unique if generated locally (if I remember well)
=> probably locally with a package - cf. https://github.com/openfoodfacts/openfoodfacts-dart/issues/370#issuecomment-1021659401
3. when the UUID must be set
=> probably at the very first init of the app, and saved in preferences

It's looked so far like uuid should be populated by a device id, but that's not supported by (agnostic) dart. Only by flutter.

**Comment by MohamedFBoussaid** [comment]
@monsieurtanuki I can give it a try with my Flutter app, and see how it will work. And then I will be back with examples 

Future<String?> _getId() async {
  var deviceInfo = DeviceInfoPlugin();
  if (Platform.isIOS) { // import 'dart:io'
    var iosDeviceInfo = await deviceInfo.iosInfo;
    return iosDeviceInfo.identifierForVendor; // unique ID on iOS
  } else {
    var androidDeviceInfo = await deviceInfo.androidInfo;
    return androidDeviceInfo.androidId; // unique ID on Android
  }
}

**Comment by MohamedFBoussaid** [comment]
Thanks @monsieurtanuki I will use that package.

**Comment by MohamedFBoussaid** [comment]
@monsieurtanuki , I have made a quick test using that package. And normally I made a fake update for a product 7613035989535 with the following UUID : 1723BE2C-C0EB-4055-8960-5534AFBFB63F. 
@stephanegigandet @teolemon is there a way to check if the UUID was received on the backend ?

**Comment by monsieurtanuki** [comment]
I've just added uuid to smoothie too (https://github.com/openfoodfacts/smooth-app/pull/1064)

**Pull request merged**
