### PR TITLE
feat: #307 - added 21 enum values for advanced search parameters

### PR DESCRIPTION
**Pull request by monsieurtanuki**
Impacted files:
* `api_searchProduct_test.dart`: additional tests on all `TagFilterType`s; refactoring
* `TagFilter.dart`: added more explicit `enum TagFilterType` as filter types

### CODE REVIEW

**Review by M123-dev — APPROVED** [review]
Looks good, thanks @monsieurtanuki 👍🏼

**Comment by monsieurtanuki** [comment]
Thank you @M123-dev!

**Comment by monsieurtanuki** [comment]
Hey @M123-dev, I've just received an email about version 1.6.0. Isn't that a bit generous to go from 1.4.0 to 1.6.0 in just a couple of `feat:`? Will your PR about country code also move us up to 1.7.0?

**Comment by M123-dev** [comment]
@monsieurtanuki we just released 1.5.0 yesterday, with getProductUri and setProductImageAngle (It was the first working automatic release #312) so it is not a jump. 

But yes a already moving up to 1.6.0 is a bit quick but luckily the version increase only happens when we merge the autorelease PR, that means we can merge as many feats and fixes as we want and the PR stays at 1.6.0, only with a breaking change (feat!: or fix!:) it would increase to 2.0.0.


Same goes for fixes, when we have x fixes merges the version goes only up by 0.0.1

**Comment by monsieurtanuki** [comment]
Ok thank you @M123-dev that's clearer. The version increase makes sense, and the fact that we still have control on when to actually release too (with the autorelease PR).

**Pull request merged**
