### PR TITLE
Minor fix (line 398)

### PR DESCRIPTION
**Pull request by kant**

### CODE REVIEW

**Comment by MohamedFBoussaid** [comment]
Thanks @kant

**Comment by MohamedFBoussaid** [comment]
@kant there is a test that is failing and this will block the merge. Can you have a look please https://github.com/openfoodfacts/openfoodfacts-dart/pull/164/checks (I don't know why it is failing, bcs your changes has nothing to do with that, but can you please try to pull the latest master again and run the tests locally with `flutter test test/ `and make sure all green ? "

**Review by MohamedFBoussaid — CHANGES_REQUESTED** [review]
@kant there is a test that is failing and this will block the merge. Can you have a look please https://github.com/openfoodfacts/openfoodfacts-dart/pull/164/checks (I don't know why it is failing, bcs your changes has nothing to do with that, but can you please try to pull the latest master again and run the tests locally with flutter test test/ and make sure all green ? "

**Review by M123-dev — APPROVED** [review]
As @MohamedFBoussaid mentioned here are no real code changes so this pr has nothing to do with the tests failing. I made #165 for the tests

**Pull request merged**
