### PR TITLE
Try to add build using GitHub actions

### PR DESCRIPTION
**Pull request by teolemon**
Try to add build using GitHub actions

### CODE REVIEW

**Comment by teolemon** [comment]
Install dependencies1s
##[error]Process completed with exit code 69.
Run pub get
Resolving dependencies...
Because openfoodfacts depends on flutter_test any from sdk which doesn't exist (the Flutter SDK is not available), version solving failed.

Flutter users should run `flutter pub get` instead of `pub get`.
##[error]Process completed with exit code 69.
  Run tests

**Comment by peterwvj** [comment]
@teolemon Any progress on this? Enable CI would be really neat. Especially now that the tests have been fixed, see #33

**Comment by teolemon** [comment]
Hey @peterwvj I've just rebased the branch
```Resolving dependencies...
Because openfoodfacts depends on flutter_test any from sdk which doesn't exist (the Flutter SDK is not available), version solving failed.```

**Comment by peterwvj** [comment]
Feel free to reopen if you resume working on this.

**Pull request closed without merging**
