### PR TITLE
feat: 831 - Open Prices API - "get prices"

### PR DESCRIPTION
**Pull request by monsieurtanuki**
### What
- First implementation around the Open Prices API: "get prices".

### Part of 
- #831

### Files
New files:
* `api_prices_test.dart`: Integration tests about the Open Prices API.
* `currency.dart`: Currency of the price.
* `get_prices_result.dart`: List of price objects returned by the "get prices" method.
* `get_prices_result.g.dart`: generated
* `get_prices_results.dart`: Either successful "get prices" result, or request validation errors.
* `location_osm_type.dart`: Type of the OpenStreetMap location object.
* `open_prices_api_client.dart`: Client calls of the Open Prices API.
* `price.dart`: Price object.
* `price.g.dart`: generated
* `validation_error.dart`: Single API request validation error.
* `validation_error.g.dart`: generated
* `validation_errors.dart`: List of single API request validation errors.
* `validation_errors.g.dart`: generated

Impacted files:
* `http_helper.dart`: minor refactoring
* `labeler.yml`: added the "prices" files
* `openfoodfacts.dart`: exported the new "prices" files

### CODE REVIEW

**Review by raphodn — COMMENTED** [review]
Thanks for your work ! I have no experience in dart, so I can't comment or review further :sweat_smile:

**Review by raphael0202 — APPROVED** [review]

**Comment by raphael0202** [comment]
Thank you for the implementation :)

**Comment by monsieurtanuki** [comment]
Thank you @raphael0202 for your review!

**Comment by monsieurtanuki** [comment]
And thank you @raphodn for your comment!

**Pull request merged**
