### PR TITLE
parse percent field of ingredients as double not as int

### PR DESCRIPTION
**Pull request by Grumpf86**
we want to parse the percent field of ingredients as double instead of int.
I've implemented this little change.

BUT the mapping of percent is not working at all.  I dont know why. Maybe just my IDE, json_serializer or flutter is broken. or I am missing something.  
test - "product ingredients with percent" is failing. 

Please do not merge until its working and approved.

### CODE REVIEW

**Comment by tzehe** [comment]
I introduced the following changes and all tests are succeeding besides the api_test_addProductImage.dart. 

Ingredient.dart
`  @JsonKey(includeIfNull: false, fromJson: JsonObject.parseDouble)
  double percent;`

when I run the api_test_addProductImage.dart I get the following errors: 

``` 

../../flutter/packages/flutter_test/lib/src/accessibility.dart:8:8: Error: Not found: 'dart:ui'
import 'dart:ui' as ui;
       ^
../../flutter/packages/flutter_test/lib/src/binding.dart:7:8: Error: Not found: 'dart:ui'
import 'dart:ui' as ui;
       ^
../../flutter/packages/flutter_test/lib/src/matchers.dart:8:8: Error: Not found: 'dart:ui'
import 'dart:ui' as ui;
```

I installed all the packages. Do you have any idea? Also which test case are you referring to? 

Best

**Comment by Grumpf86** [comment]
Hey, thanks for your help :)
I added this test in api_test_getProduct.dart
`  test('product ingredients with percent', () async {
    String barcode = "4388860154948";
    ProductResult result = await OpenFoodAPIClient.getProduct(
        barcode, User.LANGUAGE_DE);

    assert(result != null);
    assert(result.product != null);
    print("number of ingredients: " +
        result.product.ingredients.length.toString());
    assert(result.product.ingredientsText != null);
    assert(result.product.ingredients != null);
    assert(result.product.ingredients.length > 0);
    result.product.ingredients.forEach((Ingredient i) => print(i.toJson()));
    assert(result.product.ingredients.any((Ingredient i) => i.percent != null));
  });`

Can you check if it succeed? 
I will have a look on those tests in api_test_addProductImage.dart

**Comment by tzehe** [comment]
Ok will check and thanks a lot!

**Comment by PrimaelQuemerais** [comment]
> I introduced the following changes and all tests are succeeding besides the api_test_addProductImage.dart.
> 
> Ingredient.dart
> ` @JsonKey(includeIfNull: false, fromJson: JsonObject.parseDouble) double percent;`
> 
> when I run the api_test_addProductImage.dart I get the following errors:
> 
> ```
> 
> ../../flutter/packages/flutter_test/lib/src/accessibility.dart:8:8: Error: Not found: 'dart:ui'
> import 'dart:ui' as ui;
>        ^
> ../../flutter/packages/flutter_test/lib/src/binding.dart:7:8: Error: Not found: 'dart:ui'
> import 'dart:ui' as ui;
>        ^
> ../../flutter/packages/flutter_test/lib/src/matchers.dart:8:8: Error: Not found: 'dart:ui'
> import 'dart:ui' as ui;
> ```
> 
> I installed all the packages. Do you have any idea? Also which test case are you referring to?
> 
> Best

Hi tzehe,
You may be running the test using Dart Test instead of Flutter Test, I ran into this issue once.
Hope that helps

**Comment by Grumpf86** [comment]
thank God, I found the problem. there is a post processing step for all ingredients, which has only handled ingredient text and bold attribute, but not the rank and percentage value.
now ingredients are parsed as double and will be written into the resulting product object, while calling getProduct().

the product upload tests are not designed to run multiple times ... and will fail after one run, cause the image then already exists.

**Comment by tzehe** [comment]
hahah found the same spot and was working on a fix but awesome that you already pushed yours. I found also another issue with product names resulting in an empty string when you select User.Language_Undefined. If there is for example a german name it will default to the english name which is empty therefore the name will be empty. will open another issue for that.

**Comment by tzehe** [comment]
I found another issue. https://world.openfoodfacts.org/api/v0/product/4029764001807.json 

säurungsmittel zitronensäure should be percentage = 0
Mate in 100ml Getränk -> id: id: "de:Mate in 100 ml Getränk" should be 0.4

I guess the order of the ingredients is not the same because of the matching logic so iterating over the product.ingredients list to retrieve the percentage will lead to errors. 

Btw also the name of the ingredient is wrong. 

```
{rank: 1, text: Wasser, bold: false}
{rank: 2, text: Glukose-Fructosesirup, bold: false}
{rank: 3, text: Zucker, bold: false}
{rank: 4, text: Getränkegrundstoff, bold: false}
{rank: 5, text: Mate-Tee-Extrakt mit mind, bold: false}
{rank: 6, text: g Mate in 100 ml Getränk, bold: false} // <-- weird formatting should be: "Mate in 100 ml Getränk"
{rank: 7, text: Säurungsmittel Zitronensäure, percent: 0.4, bold: false}
{rank: 8, text: karamellisierter Zuckersirup, bold: false}
{rank: 9, text: Koffein, bold: false}
{rank: 10, text: natürliches Aroma, bold: false}
{rank: 11, text: Kohlensäure, bold: false}
```
I guess this is not an issue if most of the ingredients no percentage field at all or the first one as a percentage field. But if it's in the middle there will be issues.

I re added your testcase and updated the id.

```
  test('product ingredients with percent', () async {
    String barcode = "4029764001807";
    ProductResult result =
        await OpenFoodAPIClient.getProduct(barcode, User.LANGUAGE_DE);
    assert(result != null);
    assert(result.product != null);
    print("number of ingredients: " +
        result.product.ingredients.length.toString());
    assert(result.product.ingredientsText != null);
    assert(result.product.ingredients != null);
    assert(result.product.ingredients.length > 0);
    result.product.ingredients.forEach((Ingredient i) => print(i.toJson()));
    assert(result.product.ingredients.any((Ingredient i) => i.percent != null));

    // https://world.openfoodfacts.org/api/v0/product/4029764001807.json
    expect(result.product.ingredients[6].percent, 0); // säurungsmittel zitronensäure should be 0
    expect(result.product.ingredients[5].percent, 0.4); // Mate in 100ml Getränk -> id: id: "de:Mate in 100 ml Getränk" should be 0.4
  });
```

**Comment by Grumpf86** [comment]
ohh, I feared this case :) than its not a easy fix, as I supposed.

so  lets do the post processing the "right" way. (the best way I actually know)

1. use the **id** field of the ingredient.
`"id":"en:rice-noodles"`
2. download the ingredient name based on the user language, (may be we can query only one ingredient name instead of all)
https://world.openfoodfacts.org/ingredients.json (125 MB)
https://fr.openfoodfacts.org/ingredients.json
https://de.openfoodfacts.org/ingredients.json
3. override the ingredient name for the given language

**Comment by Grumpf86** [comment]
Solved this issue with commit f9fa8839059a541eb4fc3981046e1794c0e018c6
https://github.com/openfoodfacts/openfoodfacts-dart/commit/f9fa8839059a541eb4fc3981046e1794c0e018c6

**Pull request closed without merging**
