### PR TITLE
feat: add localized additives and allergens

### PR DESCRIPTION
**Pull request by goerlitz**
### What
Add support for getting localized additives and allergens

### Fixes
https://github.com/openfoodfacts/openfoodfacts-dart/issues/928

### CODE REVIEW

**Review by monsieurtanuki — COMMENTED** [review]
Hi @goerlitz!
I suspect you haven't formatted your code AND you haven't either run the code generation process: `dart run build_runner build`.
Please run it and push your code.

**Comment by goerlitz** [comment]
> Hi @goerlitz! I suspect you haven't formatted your code AND you haven't either run the code generation process: `dart run build_runner build`. Please run it and push your code.

Ooops, was a formatting issue. Should be fixed now.

**Comment by monsieurtanuki** [comment]
@goerlitz We may look rather relaxed about failing tests, but it's just an impression.
Therefore, a passing test would be appreciated:
https://github.com/openfoodfacts/openfoodfacts-dart/actions/runs/9097111898/job/25005787033?pr=929
image

**Comment by goerlitz** [comment]
> @goerlitz We may look rather relaxed about failing tests, but it's just an impression. Therefore, a passing test would be appreciated: https://github.com/openfoodfacts/openfoodfacts-dart/actions/runs/9097111898/job/25005787033?pr=929 image

I'll take a look. When I ran `dart test` locally, there were so many failing tests that I did not see this in the output.

**Comment by monsieurtanuki** [comment]
> I'll take a look. When I ran `dart test` locally, there were so many failing tests that I did not see this in the output.

I can understand that.
Just focus on "your" tests for the moment.

**Comment by goerlitz** [comment]
Alright, the test did not fetch all data needed for the comparison. Fixed now.

**Review by monsieurtanuki — APPROVED** [review]
LGTM @goerlitz, thank you and congratulations for your first contribution here!

For the record you should have run the JSON related code generator instead of writing into a `// GENERATED CODE - DO NOT MODIFY BY HAND` file.
Your code will probably be replaced by the generated code anyway, though from what I read it's highly likely that there will be no real difference.

**Comment by goerlitz** [comment]
> LGTM @goerlitz, thank you and congratulations for your first contribution here!

thanks

> For the record you should have run the JSON related code generator

I actually ran `dart run build_runner build` and did not add it manually. ;)

**Comment by monsieurtanuki** [comment]
> I actually ran dart run build_runner build and did not add it manually. ;)

I assume that the code generator generates a formatted result. And as your push is named "fix code formatting", it gives the impression that you manually formatted the code, not that you used the code generator.
Anyway, if you used the generator in the end that's good! ;)

**Comment by goerlitz** [comment]
> > I actually ran dart run build_runner build and did not add it manually. ;)
> 
> I assume that the code generator generates a formatted result. And as your push is named "fix code formatting", it gives the impression that you manually formatted the code, not that you used the code generator. Anyway, if you used the generator in the end that's good! ;)

Ah, that's what you mean.
Actually, I did not use `dart format` (or auto-formatting) initially. That's why there was an indentation issue in the non-generated file.

**Pull request merged**
