### PR TITLE
feat: #233 - new class OpenFoodFactsCountry, clearer than "cc"

### PR DESCRIPTION
**Pull request by monsieurtanuki**
New file:
* `CountryHelper.dart`: country enums and their ISO-2-codes

Impacted files:
* `AbstractQueryConfiguration.dart`: deprecated `String? cc` in favor of `OpenFoodFactsCountry? country`
* `api_getTaxonomy_test.dart`: now using `OpenFoodAPIConfiguration.globalCountry`
* `api_getTaxonomyAdditives_test.dart`: now using `OpenFoodAPIConfiguration.globalCountry`
* `api_getTaxonomyAllergens_test.dart`: now using `OpenFoodAPIConfiguration.globalCountry`
* `api_getTaxonomyCategories_test.dart`: now using `OpenFoodAPIConfiguration.globalCountry`
* `api_getTaxonomyCountries_test.dart`: now using `OpenFoodAPIConfiguration.globalCountry`
* `api_getTaxonomyIngredients_test.dart`: now using `OpenFoodAPIConfiguration.globalCountry`
* `api_getTaxonomyLabels_test.dart`: now using `OpenFoodAPIConfiguration.globalCountry`
* `api_getTaxonomyLanguages_test.dart`: now using `OpenFoodAPIConfiguration.globalCountry`
* `OpenFoodAPIConfiguration.dart`: deprecated `String? globalCC` in favor of `OpenFoodFactsCountry? globalCountry`
* `openfoodfacts.dart`: minor refactoring
* `ProductListQueryConfiguration.dart`: added parameter `OpenFoodFactsCountry? country`
* `ProductQueryConfigurations.dart`: added parameter `OpenFoodFactsCountry? country`
* `ProductSearchQueryConfiguration.dart`: added parameter `OpenFoodFactsCountry? country`
* `TaxonomyAdditive.dart`: added parameter `OpenFoodFactsCountry? country`
* `TaxonomyAllergen.dart`: added parameter `OpenFoodFactsCountry? country`
* `TaxonomyCategory.dart`: added parameter `OpenFoodFactsCountry? country`
* `TaxonomyCountry.dart`: added parameter `OpenFoodFactsCountry? country`
* `TaxonomyIngredient.dart`: added parameter `OpenFoodFactsCountry? country`
* `TaxonomyLabel.dart`: added parameter `OpenFoodFactsCountry? country`
* `TaxonomyLanguage.dart`: added parameter `OpenFoodFactsCountry? country`
* `TaxonomyQueryConfiguration.dart`: deprecated `String? cc` in favor of `OpenFoodFactsCountry? country`

### CODE REVIEW

**Comment by M123-dev** [comment]
What I read from the code yet looks good, but what about deprecating all the other cc fields keeping them long term clutters the source code

**Comment by monsieurtanuki** [comment]
@M123-dev That's similar to what happened with languages.
Not sure if my latest commit goes in your direction: I deprecated `lc` and `cc` in the subclasses too. Perhaps you meant that we should be rid of those fields instead. "decluttering" at a different level.

**Review by peterwvj — APPROVED** [review]
Looks good, thanks. Consider removing the code comments in `CountryHelper.dart`. The enum values are self explanatory, e.g.

```
...
  /// Congo
  CONGO,
...
```

**Comment by monsieurtanuki** [comment]
> Looks good, thanks. Consider removing the code comments in `CountryHelper.dart`. The enum values are self explanatory, e.g.
> 
> ```
> ...
>   /// Congo
>   CONGO,
> ...
> ```

@peterwvj The point of those comments is not to be very interesting, it's just that each enum is supposed to be commented, if not the pub.dev score may go down.

**Comment by monsieurtanuki** [comment]
@peterwvj By the way your example ("Congo") was not very lucky as there are two countries named "Congo". That's precisely where a comment would have helped ;)

@M123-dev OK to merge now or are there other actions we are waiting for?

**Comment by M123-dev** [comment]
Yes of course we can merge.

On Wednesday the automated release didn't worked because we had to publish once to extract the authentication credentials since this is a reasonable PR for a own release its fits perfectly.

**Pull request merged**
