### PR TITLE
fix: #241 Added "energy-kj"

### PR DESCRIPTION
**Pull request by vik4114**
### What
fix: #241 Added "energy-kj"

### Screenshot
image

### Fixes bug(s)
- #241 
### Part of 
- #241

### CODE REVIEW

**Comment by vik4114** [comment]
@peterwvj Please review

**Review by M123-dev — COMMENTED** [review]
Looks good to me @vik4114 , but the analyzer says that there are formatting problems. Please run `flutter format .` to fix it

**Comment by vik4114** [comment]
@M123-dev will do that

**Comment by vik4114** [comment]
@M123-dev Can you approve the workflow

**Comment by vik4114** [comment]
@g123k Sure

**Review by g123k — APPROVED** [review]
LGTM !

**Pull request merged**
