### PR TITLE
feat: #350 - new method getProductFreshness

### PR DESCRIPTION
**Pull request by monsieurtanuki**
New file:
* `ProductFreshness.dart`: Freshness of a [Product].

Impacted files:
* `api_searchProduct_test.dart`: new test about "product freshness"
* `openfoodfacts.dart`: new method `getProductFreshness`

### CODE REVIEW

**Comment by teolemon** [comment]
Can we reserve the freshness namespace for this ?
https://github.com/openfoodfacts/openfoodfacts-server/issues/5674
Score readiness or something instead ?

**Comment by monsieurtanuki** [comment]
I'm not against changing the name.

My point was to create a class (`ProductFreshness`) where we could put several different freshness or readiness fields.
Currently:
* bool isEcoscoreReady
* bool isNutriscoreReady
* bool isIngredientsReady

And maybe later
* Etag
* int lastModified

The goal being to provide a method that helps to quickly monitor the state of a product: how complete it is, and how fresh the data is.
But that's perhaps a bit redundant with the "states".
`ProductCompletionState`?

**Comment by teolemon** [comment]
- So first, Happy New Year :) 
- If we have all of that in mind, I guess it's good. In addition to product states, we also have the Product Improvements system (https://github.com/openfoodfacts/smooth-app/issues/811)

**Comment by monsieurtanuki** [comment]
Happy New Year!
@teolemon You're right, that sounds a bit like `ProductImprovement`.
We'd be better off merging that in a single class:
* bool isEcoscoreReady
* bool isNutriscoreReady
* bool isIngredientsReady
* Etag
* int lastModified
* bool ORIGINS_TO_BE_COMPLETED
* bool CATEGORIES_BUT_NO_NUTRISCORE
* bool ADD_NUTRITION_FACTS
* bool ADD_CATEGORY
* bool ADD_NUTRITION_FACTS_AND_CATEGORY
* bool OBSOLETE_NUTRITION_IMAGE

Does that make sense?

**Comment by teolemon** [comment]
it does

**Comment by monsieurtanuki** [comment]
@teolemon ping

**Review by teolemon — APPROVED** [review]

**Pull request merged**
