### PR TITLE
Add Permanent_attributes to Attribute.dart, user will always see these attributes on product page and can't toggle them off

### PR DESCRIPTION
**Pull request by jasmeet0817**

### CODE REVIEW

**Comment by jasmeet0817** [comment]
Usage: https://github.com/openfoodfacts/smooth-app/pull/606

**Review by M123-dev — APPROVED** [review]
The code has logically no problems, but is it good to put something like this in the public package. If we leave it like this, we should definitely add a note to the comment that this is used for smoothie and has no further influence for the package users.

**Comment by monsieurtanuki** [comment]
> The code has logically no problems, but is it good to put something like this in the public package. If we leave it like this, we should definitely add a note to the comment that this is used for smoothie and has no further influence for the package users.

My 2 cents: I agree with @M123-dev - it looks like it should apply only to smoothie and I would not pollute the library with irrelevant code. I would put the permanent attributes directly in smoothie instead.

**Comment by stephanegigandet** [comment]
Agreed, this behaviour is specific to Smoothie, it should not be hardcoded in the Dart package.

**Comment by peterwvj** [comment]
I agree with the above comments. Please don't merge.

**Comment by jasmeet0817** [comment]
Oh yes, most definitely a good point, sorry I missed it, will revert

**Pull request closed without merging**
