### PR TITLE
fix!: removed deprecated code

### PR DESCRIPTION
**Pull request by monsieurtanuki**
### What
- Removed deprecated code, as we're about to merge another PR that is a breaking change too.

### CODE REVIEW

**Review by g123k — APPROVED** [review]
👍

**Comment by monsieurtanuki** [comment]
Thank you @g123k for your review!

**Review by peterwvj — APPROVED** [review]
Great, thanks!

**Comment by monsieurtanuki** [comment]
Thank you @peterwvj for your review!

As it's a rather useless PR (only removed deprecated code) but still a breaking change, I prefer to wait for #790 (also a breaking change) so that we can make a single breaking change release with 2 breaking change PRs.

**Pull request merged**
